"""create initial schema

Revision ID: 5c0430508f9a
Revises: 
Create Date: 2026-08-22 15:00:51.651188
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5c0430508f9a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_terms',
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('term_no', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint('start_date < end_date', name=op.f('ck_academic_terms_date_order_valid')),
    sa.CheckConstraint('term_no IN (1, 2)', name=op.f('ck_academic_terms_term_no_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_terms')),
    sa.UniqueConstraint('academic_year', 'term_no', name=op.f('uq_academic_terms_academic_year_term_no')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_academic_terms_is_default'), 'academic_terms', ['is_default'], unique=False)
    op.create_table('activity_categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_activity_categories_name')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('campuses',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campuses')),
    sa.UniqueConstraint('code', name=op.f('uq_campuses_code')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('club_categories',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_club_categories_name')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('colleges',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('primary_campus_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['primary_campus_id'], ['campuses.id'], name=op.f('fk_colleges_primary_campus_id_campuses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colleges')),
    sa.UniqueConstraint('code', name=op.f('uq_colleges_code')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_colleges_primary_campus_id'), 'colleges', ['primary_campus_id'], unique=False)
    op.create_table('venues',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('campus_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('venue_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_venues_capacity_positive')),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], name=op.f('fk_venues_campus_id_campuses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues')),
    sa.UniqueConstraint('code', name=op.f('uq_venues_code')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_venues_campus_active', 'venues', ['campus_id', 'is_active'], unique=False)
    op.create_table('majors',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('college_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('duration_years', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint('duration_years BETWEEN 1 AND 8', name=op.f('ck_majors_duration_valid')),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_majors_college_id_colleges')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_majors')),
    sa.UniqueConstraint('code', name=op.f('uq_majors_code')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_majors_college_active', 'majors', ['college_id', 'is_active'], unique=False)
    op.create_table('students',
    sa.Column('student_no', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('college_id', sa.BigInteger(), nullable=False),
    sa.Column('major_id', sa.BigInteger(), nullable=False),
    sa.Column('enrollment_year', sa.SmallInteger(), nullable=False),
    sa.Column('grade_no', sa.SmallInteger(), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("status IN ('active', 'graduated', 'suspended')", name=op.f('ck_students_status_valid')),
    sa.CheckConstraint('grade_no BETWEEN 1 AND 8', name=op.f('ck_students_grade_valid')),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], name=op.f('fk_students_college_id_colleges')),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], name=op.f('fk_students_major_id_majors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students')),
    sa.UniqueConstraint('student_no', name=op.f('uq_students_student_no')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_students_college_major_status', 'students', ['college_id', 'major_id', 'status'], unique=False)
    op.create_index('ix_students_year_grade', 'students', ['enrollment_year', 'grade_no'], unique=False)
    op.create_table('clubs',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('home_campus_id', sa.BigInteger(), nullable=False),
    sa.Column('advisor_name', sa.String(length=50), nullable=True),
    sa.Column('leader_student_id', sa.BigInteger(), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_clubs_status_valid')),
    sa.ForeignKeyConstraint(['category_id'], ['club_categories.id'], name=op.f('fk_clubs_category_id_club_categories')),
    sa.ForeignKeyConstraint(['home_campus_id'], ['campuses.id'], name=op.f('fk_clubs_home_campus_id_campuses')),
    sa.ForeignKeyConstraint(['leader_student_id'], ['students.id'], name=op.f('fk_clubs_leader_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs')),
    sa.UniqueConstraint('code', name=op.f('uq_clubs_code')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_clubs_category_campus_status', 'clubs', ['category_id', 'home_campus_id', 'status'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), server_default='student', nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'club_manager', 'student')", name=op.f('ck_users_role_valid')),
    sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f('ck_users_status_valid')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_users_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('student_id', name=op.f('uq_users_student_id')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users_role_status', 'users', ['role', 'status'], unique=False)
    op.create_table('activities',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('term_id', sa.BigInteger(), nullable=False),
    sa.Column('venue_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'published', 'completed', 'cancelled')", name=op.f('ck_activities_status_valid')),
    sa.CheckConstraint('capacity > 0', name=op.f('ck_activities_capacity_positive')),
    sa.CheckConstraint('start_time < end_time', name=op.f('ck_activities_time_order_valid')),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], name=op.f('fk_activities_category_id_activity_categories')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_activities_club_id_clubs')),
    sa.ForeignKeyConstraint(['term_id'], ['academic_terms.id'], name=op.f('fk_activities_term_id_academic_terms')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_activities_venue_id_venues')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities')),
    sa.UniqueConstraint('code', name=op.f('uq_activities_code')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_activities_club_status', 'activities', ['club_id', 'status'], unique=False)
    op.create_index('ix_activities_term_status_start', 'activities', ['term_id', 'status', 'start_time'], unique=False)
    op.create_index('ix_activities_venue_start', 'activities', ['venue_id', 'start_time'], unique=False)
    op.create_table('agent_conversations',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_conversations')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_agent_conversations_user_updated', 'agent_conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('club_memberships',
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='member', nullable=False),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("role IN ('member', 'core', 'leader')", name=op.f('ck_club_memberships_role_valid')),
    sa.CheckConstraint("status IN ('active', 'inactive')", name=op.f('ck_club_memberships_status_valid')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_memberships_club_id_clubs')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_club_memberships_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_memberships')),
    sa.UniqueConstraint('club_id', 'student_id', name=op.f('uq_club_memberships_club_id_student_id')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_memberships_club_status', 'club_memberships', ['club_id', 'status'], unique=False)
    op.create_index('ix_memberships_student_status', 'club_memberships', ['student_id', 'status'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_revoked_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_tokens')),
    sa.UniqueConstraint('jti', name=op.f('uq_revoked_tokens_jti')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_revoked_tokens_expires_at', 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False)
    op.create_table('user_club_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('club_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='manager', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("role IN ('manager')", name=op.f('ck_user_club_roles_role_valid')),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_user_club_roles_club_id_clubs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_club_roles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_club_roles')),
    sa.UniqueConstraint('user_id', 'club_id', name=op.f('uq_user_club_roles_user_id_club_id')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('activity_registrations',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('register_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='registered', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='web', nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("source IN ('web', 'import', 'generated')", name=op.f('ck_activity_registrations_source_valid')),
    sa.CheckConstraint("status IN ('registered', 'cancelled', 'waitlisted')", name=op.f('ck_activity_registrations_status_valid')),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_registrations_activity_id_activities')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_activity_registrations_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_registrations')),
    sa.UniqueConstraint('activity_id', 'student_id', name=op.f('uq_activity_registrations_activity_id_student_id')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_registrations_activity_status', 'activity_registrations', ['activity_id', 'status'], unique=False)
    op.create_index('ix_registrations_student_status', 'activity_registrations', ['student_id', 'status'], unique=False)
    op.create_table('agent_messages',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tool_calls_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_agent_messages_role_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], name=op.f('fk_agent_messages_conversation_id_agent_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_messages')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_agent_messages_conversation_created', 'agent_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('activity_attendance',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('registration_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='absent', nullable=False),
    sa.Column('checkin_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.CheckConstraint("status IN ('present', 'late', 'absent')", name=op.f('ck_activity_attendance_status_valid')),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_attendance_activity_id_activities')),
    sa.ForeignKeyConstraint(['registration_id'], ['activity_registrations.id'], name=op.f('fk_activity_attendance_registration_id_activity_registrations')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_activity_attendance_student_id_students')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_attendance')),
    sa.UniqueConstraint('activity_id', 'student_id', name=op.f('uq_activity_attendance_activity_id_student_id')),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_attendance_activity_status', 'activity_attendance', ['activity_id', 'status'], unique=False)
    op.create_index('ix_attendance_student_status', 'activity_attendance', ['student_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_student_status', table_name='activity_attendance')
    op.drop_index('ix_attendance_activity_status', table_name='activity_attendance')
    op.drop_table('activity_attendance')
    op.drop_index('ix_agent_messages_conversation_created', table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('ix_registrations_student_status', table_name='activity_registrations')
    op.drop_index('ix_registrations_activity_status', table_name='activity_registrations')
    op.drop_table('activity_registrations')
    op.drop_table('user_club_roles')
    op.drop_index(op.f('ix_revoked_tokens_user_id'), table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_expires_at', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index('ix_memberships_student_status', table_name='club_memberships')
    op.drop_index('ix_memberships_club_status', table_name='club_memberships')
    op.drop_table('club_memberships')
    op.drop_index('ix_agent_conversations_user_updated', table_name='agent_conversations')
    op.drop_table('agent_conversations')
    op.drop_index('ix_activities_venue_start', table_name='activities')
    op.drop_index('ix_activities_term_status_start', table_name='activities')
    op.drop_index('ix_activities_club_status', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_users_role_status', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_clubs_category_campus_status', table_name='clubs')
    op.drop_table('clubs')
    op.drop_index('ix_students_year_grade', table_name='students')
    op.drop_index('ix_students_college_major_status', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_majors_college_active', table_name='majors')
    op.drop_table('majors')
    op.drop_index('ix_venues_campus_active', table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_colleges_primary_campus_id'), table_name='colleges')
    op.drop_table('colleges')
    op.drop_table('club_categories')
    op.drop_table('campuses')
    op.drop_table('activity_categories')
    op.drop_index(op.f('ix_academic_terms_is_default'), table_name='academic_terms')
    op.drop_table('academic_terms')
    # ### end Alembic commands ###
